---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-notify
  namespace: monitoring
spec:
  encryptedData:
    discord-webhook-url: AgCB/xY+lW4ZwStMcF9CXTbwFeZWFRjyiMMHN6hwSJS704CXPsX7v9JxsbaSFlCNN7sfIyBhVRuDE839gg2tkffi93MpGwVGADJGpBnY8OByRJyGe9bhiSju3KCLDbijV/eyQ9JsYsHHRZvjmCLowKxqC6zYfAYoSsoHVAQgr/0Km0M/wNj3kNfXb+4YO10kyTotbzgUg9KGHkM0dVtjR1k0fkvam1Ya2WqTMcdU6nGY0MsjKlWRaA0HbOq5+VIpfk2bcrhzIC/VQPczgoIStimJLSmvAOARR/WjiBqafJOZmMBEzcX2ilufO7eDA5BlavsdszJerd3lETLtTSTGipHmDlrpLZfL8jatOSvU1EtXlODJP79mWuWMXcybkQdBZ2QSLQApRCCFYS4RyekJ2FklSzFONZGHcn2QI+vLRaA2CT54B1gg9vsJKJzoibOjkvMmIrIYSEIsBhaBUkXuq5Gg+VtyKXFzyGf6aDidram0PRhtW3HcGKkHG4eRz3ZRVCi2nffNk+faYUlHyWlZlqIuvkA92+XrILAIQnnigLoKYZtBmOV3FU/Jl7i0lXI5W9toNY1RMvDwWpR90DL1KTs3Y620Fh63WSZUpGhOPZ/6xpUwXa9Z5SicQNnOvSX3K3b+6yC7EfuXPzfPqahJP7A5sTwzd03FHy/9r6QdrPAnYpB7PbWoQWd10IvzWX05ckrwSHfAwD6eJ/TXfTS/eORfe1RBtzkNYwSWagtA6JaJgRT4Ti/ckha8rGthvNZeudTdzE+414O8/9MaMxTHonYTuXky80/hYL1KWf1Q4TkN9deKM9nbXetkgtZZLYggPqIk05OaRdZDk1XHmF/HbchVpGLLTXByNFC+
  template:
    metadata:
      name: alertmanager-notify
      namespace: monitoring
