---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    discord-webhook-url: AgA06sKXSOjAD3liMs00Q+3NK4IhvkP8y9rE+9Srk8QtgrUoDIMfM13pYKcOA7T+fyQG8F3PzcuSnywYV7aZqGhLxalwJ+uRJFGHNLTePFMb182Y0dyw0JPypCrcOw60shnfJC+gnN3g7w0HE1pqXLaf8osLmMMOuo81yp61MtI6U6gDupDCB1vGH7OKgJ+x8Rrm74r4QFD0sP3tncGTxKx37so5pyEXv3VIo3maMIBRYXEeqYs5LiUcmmWocrYxuNicTxXlAfllgZiKBwM8jJ1oAyoQB5OvnlFk9aOcdZkuu3bIR4Zh5vIZR2uVvJCnYKmy2hxAjqH0iv1eXoiTvsRWmb79Zi6h7piRmVKbjRT3dTXIOF7LlGTNV+MuSjIv+zdAjrVn3f6C1KgttfqMQfRhg7nVJ2XtU+oEgy73N8LZEfg6HN0RhC5LPP83rZa/1xnOLatntsG6x60xDeyeWGYbOR9vlQojuis+zsn274KAQiD0pxoVbEaZ6oEzSS5lRGCBIYyatTbCzVS0VbuZk/qY+fA2NjKjC6fccik6F6cqrgjiBK40Ox4Xeldj2xaVt3AADNz5tZkAr9HpxKRrdjO1JTduM+O9Fos0Zlcbp8llIu+0NcbpsCWtOL2qhZhN4XwirMQyX4rSS8Tie59uHB4DRgJpWFEuffSXIt/uUUZvi7koUX70tB+W2QMKt1tSvItXNK6bzA37jaA54XiVg89CMs9wYgv57ElRWBBL/fHPzNxkwVsQflzAiTakTngXi7l1YMiQ8nadQfna9ga/zXelbZV4DigorZ+LPV17uqqDlnSLsV9nYpzeZRppRjTOR656kUdMCl9Pul5t/N8RaXY6htzSkWxvEXym
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
