---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rest-server-htpasswd
  namespace: backups
spec:
  encryptedData:
    htpasswd: AgB2Zr2+qFczY+vp6fxS4ZyE7qAgajDYQbVm/Hm0xDbBoDTlEkwmjE+2qOxWhVuX1xJhozQpdq7v2rdBqMneTx+z9ooE449JqDfdvKBwDmydPuLypGXWJhF7/5EnxNRRTJCJTgmOxSA/+OH+oYzjO0SARG6VDl/CdicPbSXq78NVDKehuPlkuuw04oi36UNO3HJ6WSYtSeOBSz2MGpWrC24l3AEqEZjbUogykzOQSYmBfvjFqUx9mooWY/WZBv1OSZwSnSRi6YDS2Xyly/mbhjgpueDtLi9JZivPuouuiPDeChKlAn/z0MTB3lmj/zhDBqiI62Z+j+D79TFKImt9uMwlU7Cpd2xY6hyrI/oz/6Kdsbk2fvdJckONF1GsQHeJYJug2Ey7YLnBez2IetaXflTLN9HysRly3dPzDZVO/+J+MhgpWD6sCyoC+j361G829JEk48KKFucGyuwHhN1Rfpw7X+uT9UKOLxf+MfvMcUz3wCQq00eGMYsGvQkGLGWv3oynV4DD8+ZVh2He/v+iNM8GpCtCpAyDsE/+yqei+Ga99dBiiNES0F+SHr4zKO8b70B/pQl7JZGcoM15NM7rT5yWeL5qPx5zajS1j722m6+Q2Ze0coBPpit1CfFCZe9nyQqYrNMjB8vSerPHK11m/ComtC14TgBOobZuSXl0ZVLBfAJs20pZHzo3A75HAVGeYmY8pX/WQ6zLzprMGdqaOhftPChO7G3cWS1dEdnChZLfd5eCGnaorsfGxTnUovxcwEoqguYP4tEdcNPT8HCeauz9XaouRodWBmo3BytfQNZecP3vfSuXm5XfmNpGXq5+5hCqTjLdUFwtm5YoVXoT/fE9jHUrXNvCpKBW3mVoMEzCHUyXS/5Q16EZwFXwr+MnlBeXPuuPQvbpSRjMTsNgMCGxq1IHiojx+DTmxn6MarFFoQvB+ppYPktrnlPun45Da8hXT1GQO9kacQnm7bgqXm9R+ori
  template:
    metadata:
      name: rest-server-htpasswd
      namespace: backups
