---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: networking
spec:
  encryptedData:
    token: AgA7uo1teEUzRaMRw8WPJH5SvwcpvN4bB/90rMLDYYU927mFHrkp+ykJROiei+9Q7dH0OaZAlFOUrxtRw7nduaQ7JFVfGYCFA0/erLZVxvsNvycNm9NAX9jnQDtgojtIz4rrFetzvYEjkUxL455Y3DVdYuIsa3Sz3xjo31r27NFjMHrfduf+T+KV4nLjol9O0J8S24UX9tgdYoWyElCQBmEmZdv9GtidxscwItwca5x7G9btj4hUeJ5JsQak7I0tmtsTEGtI8bDQoy3mp6f0KQX1DVtHmgm5j4W9eNdwwk+4WHhnRi9KuBKbYz7VVI+UXjmKFs051bdWJYfI/xUaGcMJS2gAImrJrcMTOzMpOGRd42W4Ltc7I9Cvs7bk/aM4s7K8W+cETWNjQ3tGw75B8fzvVZcwVljjU5WIxGUl9sH5JCZxsQSq/7Q6qtfCY995SnZXgGZPWS4hP5UX1WJaNpacOuE7YLjcgbgK3v/hybHLbrWjrhWU6laY2zSjxljo+LxXk3tXb9hIGKteZS7M/vxkDhRLUyLwofYJFo279NGuqEQRu2Wcvrh5XfoZFhXWGWENvmd05x7nLbaa25siHjVLMFnnmj8gmBcEY5EXe1f1i4f45URgAvI6WwTlxCILDut+yHwLlzveg8Gln3wNY73pPNR2gatdKj+GWUlPvflbeQ5CusFb8zQP+nuVM8cDp265s9USa+BxMxnq4KufMpcB6Vh44sag91HaJ8N8IcoyDRcEEwRmnob+R9fTT+LdAcmm0gd7iVoulLSbVSvvcSNDxJ07nw/Dk40ctGFtHPrejBLJYOiV31XNbPOGalUW7zNz/5Ao5kdVUdG+yXPmjTghBAgEOihl0/mfQ9HxEzx8JKF/4BipTZ0mMd9z6xs3mj/mWSlHldmtZBqS4MHjGYfjB1A4CDALcGhb/RTn1Lh+RGt//yb+nWqu/oaZMYapLafNM5AkEJGSsNydksKVkVw738DeFV6KNr2nU7ipd+GQbI7ojoE83eUDbrW3+qSZmkM=
  template:
    metadata:
      name: cloudflared-token
      namespace: networking
