---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAyilWcvjOE29VFK3ybei1qI02zRrqh9PS0B28XSWHVNMjugohagl+OxSworC76S7JhC41LyIgyqu9AG5IFUHtTxQvF6gvfbMhClBQKVFlWRCqgK4Ljc2yDzLLyLGfGqFwiVOSNwuR8y22P8J5uFYIKrw+o+QnjDRIQPGzwKV0VB0bfuxG664oCR8wDxqJBvGi9FtD3jDpiIB0dUy69BmGstb66FpMWfg9Vs6wNt9D6PTTssRZjGqiishrq0m+j8dpEAckElG+So+k+Fyy6s6IiF6nbeM9Sbyq3qO4Mo+2T7Mmrx5NMuY9oFjLvcIGpmMnYTg5sPdsnKBHDvJeFZhm1QfJE+PThL0fIQTjeVA9fkf9CzRTkotNao4rE89gqZpB+oJoSlotw0bdX3V+SVJmkWhq8mBhJZdsEFIlyIkrO6Z6CQ5XQnrxS0z24GHkCocFzI5ArbsU0XIMyiUGZnlROYBzOV/5ji1cVVTYuFnK3nTJUV3XzNrjUycQ29zcOoiCAu/rWLffGbW0hb31bnM8qRXEoCgO3S96XAoiWZ46+S0CcxpG2PFXCULdpWhOhqMvZZ84sWoiEB05U7md0GAwt962rWq8t7TmvG5sOrRetZZT3RYFKiIJpoov67bTvw9WjtGIfMr6ADWHFfMR9OFsZfK4cNHrd+osYrcua/vRuxiHEQN78srd9hlaffIjHJIqBYsFHaAzZQO9x8SOHpj6AftXMQ1gfd2ZFP5O8cc4h
    admin-user: AgBfqCcdDYovZGlRe4nxHW/MGO5255mSdm4iXeI/A26xIJnsFXCIL6xIOt167mxdtWiDwJTgyUhBaRn++1RO0DjdtxBoLMraEuKgoqh4MlcRlwB/tN7XorCEkBb8bP4ZPeiIxK/5oWOlY2DtMX179NCzoxlufH5QIBR5o/lJkU+gDBqpK1qPk7uGNUb6qHboZPidT6JXDhC1nApXk3HOZ3HsGxHXpbRldlTaX5BWBqii3cDGQWnz+iQ94m26mNYzEyD1CMNgpN88eNDMIZy9DQVLTjVJ2Ip4wpwn2tDFFcQ1nziRagnAopeeriluUJQFqz7HAiF8+YcuYg8ZDX3iWD62O7miJHpT4G3tWGZES32BInJW2DCGUXp1VDyZAE2+TlxHEQDvbQRlmK/BN4JUspbSmSmR75rW//Vz9e+ELALMIvjlyZSaXOAh87PXiWgmbC6kcynpw4D+ob8M0B2gzGY1KOBdRwyDURvZtWuLvgDqQb73+psAcXMOKjaXSD3zB85yruqEoVYp738xQQrhLTnBzF2JlruxpILuztqBFFHo5vy0EtJc1fh9lKKW+DyuICMuk3y3Gu8Rv1dSAX1ui10Y0u/d9ZJ8FQsDAfIdVGc0EhRdnJs/YeGOYdTJ3Lbi5eAd+jqsNK+LlnByvUFg6Dzxa6qNlIAMS208r/Nlkse6GNwRlu934aMkRaLnGcVlsr999qeOzw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
