---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgCfebJ3JjHZAhUU/CcgsVOTGLGcorDek+OIojzyNci+CaX6B8oMjAaLf6PNh2FZUOZFIyQfs3OZQ4jnFZGqoGVo1KI1ySzTkvcGQZGh4eDFJ3wivzWQJZE9f2fLTx/d1O9IGCwFvsCgfIQeVL6bck6UwdeKlJs1gJJGRddLP71mGCBSn2Z1u8W8zfB7WD2/Qrx+0xYq8B9+v7OEJ6+8XFODCuAmBqpdSi50ArE+oZvwGPIem/HZLKluPXs0+UWzyuqILBPewBufvqZoGw8ZGf78YICJye808ss75Q3x1tDs78KarRbpc//4JMweFc5CwI/UynAZczqvX19HawFc6mAdQU92KaV9iqrllCSIsWzfw4ttoGKWznBovpdJeT6QfMlxvlARdlMNMzzkl/Rtvfl4Iroyr1BDu7SUWGE5HjubdXH+NpOtqwA6gs+AivXWNgzFl2eShqa403XER5LrTwnDJd+Z9y/qGPGL/FqpaSWPOJpr44I+BqR+RdH3BCWYm8MHkJYdT/J7VsxR7Y0KcVoLTGLEc5oT7p4rlXXn5asZvIuvnq4Dw8YoN7Zr/sDFwCeSg5H8LKOZZI4Rdj1QMo1wZxbCo36In85gFXkCM1kOTu0+xMALHNqpWiXOMi1gASDIHaRVjREAeptnPaPbUGtBH2+eI1tIT/HORA0abrYcB57KVfs+Tsn6OJNBnmuPkbgkK8d3FqWvhobNLO0gWTX8Vw==
    client_secret: AgChqW/+Z+R9Or5obkdpr+vcfT3uiDMet0bz2M6vP8P+0mdguskqOLGgj+HvkPhikFaXGHeuIYJmOt8qOjXoe6t44ieKeAL9JkDFHub9FezX0gb2GTeDszBnwAn1oloi1lmCDBBS2PEJRovZ28YEE44CKXyMu+RrdYbOR8GQqmAmz59lM7BBnN3LU80GEKt3XCydS1jAmmjQzkMg8vr0KwQT6UbigdNSM0ukZoYgfvJBpky4VmgXPIWu5ENvP+rZNWB/3X6zq37IlGaWh+sq6gWTqkEKwnL1hxJQGC2RcsGJfGYDsUy3rQrIhxY6zsm+bkJ2xqKMafuZpqejHdIhmDecVxNC/qY4sPnrOtNYI02VuhIisEwvt8gt5TIs7UfE6j4kiToSjyDCojTtnW9KPq3t6W24UOKuzNioqxS31AByTo7uV7Lxoj0BWtpDnIeAzIYnmyK7OLskv8v4BuWrL0NJ6os9KozRTw/a65oysfuBxGwP7FUayIFw3EDD+b0Bo68Ln7N15irp+XnJ359YY/HcJ83ByDgLFnYVqTkYRAxAymXg7RezRPjkmNqqZ4S3jF21ngNUQmi1eIhgB5ipbzJKAErzmWjfDE9npZE37uGvFG1bnMK0DE+CJE9MKwl6G5DU2kJnAkaKpg3JAjw67QTpOB0RXJBBncloD9vrMwZqV/75FIgMQ3p/JiVFACdkfk4PRh6D/fwDOhxEq2RxBgBjUUYybHyEF6ixTJiFI9ohx1SAs8ekkMJ959XyySafutkPYs5VtQLPKpKu7bQNos8=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
