---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-notify
  namespace: monitoring
spec:
  encryptedData:
    discord-webhook-url: AgAQpQxnWlByiPYgTkm3DDuPJ3AJ7fYnmPJDkwxADjyYcdpTU5cgYqXRXT9IMctax5+R/vC2zeWc1BGWAikVZJZwdDgXpGo0E47R3PtNY11WHPF74fJttBB/U4TbR5ottTkbtCBcrGx2vgUK5Vk1Kj6+pu/jCAJWZhUuUpNBykEqB2dnZvQoR1gRWL2Rn8dyr1Igw0TTikUsgCcZ7gZHXqUI9f8R02BQa8AGILBxV3Za1tmar5Ub9MZBQXmg4ff1u6LlDVSJ0vk54iE71l9L9MBji2hQAoqEVEq5gEANBPH8iJYRYNWXSdIkeBeL9cYp9EGzSTRsniT9uoBZQ6yts7TE3MrSb2ywtd4wVB5DgTxXrFZguEQQUYUatWcs5JiA4mVmVnhLNjz9Lq/lz6GfYhYvGDW6BCG6eWRO2wVPKLXAZkjKXjcYT943D6Ta2JEuBbJmV2EhvvovYV+2VoH5v7hDsAXAGgHPJGPEVeseOVlKBNr05k9vesLuJMwatOF3OQI/fhlgAiPXsLf6AexciXgtoRodXAgn8ZP4Jda1/Lbcvy/xedZ2OLZZGXw+NsQ7F/7GIbRntrMMra+ZDples2EWG66LEttpVEPkshv8R7FpQ2GlmILejJXWv2d4BdjBqXg4+pKpo7sEOvdczDIV+VS2rOv1JkGnuybjsEfsh4pn/8PWLC1LtYIMTsrKDSNiEJWUVfwLkDcdoINWHDu3VQ+dTd8i5xVeNark0mXPsQAnN0OeH/9ntg7eC9ZoI0nXCn4l0ocvp/EjedeAXW++ePqbG4io62+Y5vXQN2WGLvFaYJ4BPlR+fvdr+znWIQtuUeFmoBVGsZYDJDOEkYrqYHtsagNGsKNITYNrHA==
  template:
    metadata:
      name: alertmanager-notify
      namespace: monitoring
