---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBD7zbfraFFnJ9aGZaPMjwlyMs9sss6onjXWdApfHbVPtpqKReFA0p57OcqN6fyNsFstyKrpbWlidV3K2oLihK3cshx53f4o8Jp6rPDLH5cMVfkXrxyFPupHrYubYGqH1ym+OaWqZwsuzxs6CwNUvQrBJqcZ4JEUc9TcazCQtvWacFBTVC6waVheHOHoIdMCFMQqOtXTZUqG1N2Bk2dHSxaYkkF4OKVCY95BDYqDPvyL8Nl11qoH2CU6O3J8kUg0bkhdAGTxlFLbNpOmhiKLkuhQHizJYorhrn4sTWyBiwUII2cfCM4IXK82Elxs+mKc0HdgDSdydyg9xzt2m3nlirS2aqemeOx3N76ZZ+jV3TSpUvePOGh1+eGu4Dc2COYsBX2Y3rtgLkV49aXA4QlBR5RCEAY5PTyJYikyYNajnjc5L/flCm1+hd6X1L/RO0dbIYBr4ho62noZDuQdsBnrcqgUCFM0FzvadJQUJPstXLOC8e7mUOWTRJSqAvYTd1S2WX9W6kmQY1fF+mKiqooGNf/ejy1dXKxPvTH58YpCdFEeJXTePGgFCqcEekZwQW1KXmbeJdYX5Tt3nsdwCDPhfown3DL40pVkybwszNFRx8xz3Aoqrh0V3sJafBKLuNuY6ZKbi0jb7zfqZZ0SqDVXxxOenAPDkJGWav6/vfWNYRZir9r7lzz1Qp4KA6OK2RRcfX/O/3yO+rYeP11YEe4MdIqT/xQm7+k/MLiYI+jaEuqXCZX+x3tdtONLdhSzu/XfTxeAL8VKQ==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
