---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  encryptedData:
    ADMIN_TOKEN: AgATgM7nN3CmfL5utz5z1kkkxq0pApKGJhAw1LyGbHtTqP2wEzi0w8HceJN7s+jo1k618IyYRGcnJ9ob01InZ1CDzebcbWEzR8et7iUhz6Ro/BakyMlILm2VB4znTZFrhc1CMdWf8bate8iiQ8wLbnmjZ03HT1o1beqkvcc/u+dNXTPXqGxci7FOqj1/BlReeFyrDD2C6Kyb4X1my7ZixsVvsVa7HSHb38Rzy7NtGr39SwX1dZXiRnvyS4jdSknD0oApgs0A6YugylRf5sU413mqYK9N0SiVF3pu+jEXqW7Rz60k4NzO/j60lmqz3XqfpM2wwt4P8bxEUJ8sAqmyo/dDL8ZUMpfZiE4oXS47ojDNCjvxHdidLdzE7n58MP+GoLYS8bY9l5RSlPHjvdwkmkUMOPBMcQoYUhiFhw1+S6DA9pGFLyAR9FWdQIzV1rjlORAe5d8Sk42HGwUTdke8X0IerMZIuMaWqf7tLm8Mez6oMHB3RUH/o/ZbVLd73410FR1kjA46ZQV5thipIBLF9jPmoVMmWWNmHBbGzdDyQNHCtieIfGwYewnwiZplQeEx58OhYTrLLhMdoU32S624ZWqtq44oM3ifI5JERCrZAkJu7QuOEj0gmlEcMUVLHZ5RtZy8nnrwRZxFIwkt2VUw1RuBAXWq1nCeBbZNyPKLA9lMRq309SyoyPs2Ml+I33BsLZnIqEsJNg4FsR0Tg44nu9DzLzzMfQR+3oTHt2E3kugxgvI73EUSwMIq+t2wfM6YFJT4yHy/rlGoIc8xQejuI00xHV08C2MJvIWtQs6VgJad8n4vPK5n4sDTRbvbW1WHUaCHhmLDw+M6V7PSFqKTVoFQk5B/C7zE
  template:
    metadata:
      name: vaultwarden
      namespace: vaultwarden
