---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: papra
  namespace: documents
spec:
  encryptedData:
    AUTH_SECRET: AgAAJ1C1tB1dpZvBwBi70VU5dVQWXm9q2bOverGHDx/ZWOTAzed+Xkj48yutyK4Dw2lbiapePjkXb7ERe2pdzndNM5+4Fv8KzMO4r2WyHF2ecPokfpulv+nCpCFLf7zjzd3eolzVu5a8rkMaFL+M05DFdkdReMgtrl3Uy5bt6iOgoUvsDgBgL8zvsFmRmuGLTuKNEOocvDmUJi1v4qWbr3x76FzjgBJYxjiUVsZ1Uh5HYtS5dshHMZnj16XwtTtj2jqLNjboUlEVGgLHBIqUfEMBv/gTmNLbnGUqGTERjA8zMSW6EZjfo3Xm9GfHGr8oOYKs1/2qJe0YejJ1hrvp05PQVWLwIbrD8YfEDEZLr0gecArJkOJ2aELa8rd5MqAYL/ZXSi6HqRXismD9L6V7u6XetqB/t/GFPEhes8pbs05uogBFTmhDnu9nOcJrsE89fm7+IvUkhXaD+e2WXi3nrs98j3a8rP16gzu294xYNniPzF2FCom8uEBRgV2PaMiqrgNYFmy1v3qiZIjJA4Fl2RY91XhejuksyXgIC1J7mqc6V0IWiMGNQFZeKW7xMHlK1u5SZh8GPBXqZvpzWmOj90R/RNhC95ZkHm9772qnHASXZNF5HW1x5h1q9ozFsfvjjyp01NxUcSRKUcPx8xEnbl6BFF9Edv6hvWVXS/UWc09srwDphMKDtbXgq0Ef0rYeq7cxhoJlssQpr+/TrI0nk8qXTl5FTJcQVuN67WezKHE0J+biqS3dymYyagsU+qGqRXzelvZiv26AkinNqgA2jTx+x04S9OTgd8u9GpxaghIjCWzfBWuH6DUC4VAbZ+wRJUg=
  template:
    metadata:
      name: papra
      namespace: documents
