---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gokapi-r2
  namespace: share
spec:
  encryptedData:
    access-key-id: AgAIC8rCAKlH43gisyAmEDvWCI9s1+415iMJ7G6xHDQbFGnoirilP9mQCxKcoulNixyLRTk+kmXCS0Ky3FjxH2OBpTX5eBf5/13ZCBCLixysO1uozBPCbTPSVkCY1oY3+ukgSfKNsPX3YiQmXaxWRgdl9LZn/C3z+oUA5KGw/I/1I53IBSI0rJ/dFnnw+x7vhVgs1BwnEl/hsQ0Hr+C8/ofL0RHcYfgeAaWT87TJfrJmyFpHDziwtB2yG+gcEh1AxLKUcKED8zhm+pYaK6m5AQz3wlMx+/cuqb50NiEdiNL8QwNHlvW4RE+rQ4FJcb0KCwkaU/Zjtgxq/5t5X1j4ej2/Q1FDShD14raBTTtwiuOzN6u0L0ACG4YbqQ5Xv+BSiP3SYF9VvBJq3ybmu5novP/X5ilZLwcyuZ8O/Ueg0F2+buOZmlBhadGQGiB2x2hFysEryHoS8HnK0Tjd91zs3ruXWNVHBGyKhC5Zt8tuzIpCDgZML+xTkRoD90peTfW3z9ByOBiLDctu60Ajwaaio79duL/1NT/qDoeg70DGtCOSw2fFeTZXByo1gSpjdW+B00UdV7qZx97RgY6YboJMuNbSBgjLMccHcC6ko2uOhx/p/q/lw35kNpVM0NCFtKnL+AorG/OnBC7re9rpRuSJPDo+EjWzdDXv2yz5+HuWyGANX95VtOUEmXZbJmwgJl5WZJmZmVySwRmV1NvlCTZnSeaaE4nK+QAz5n+UoURgNFn8HQ==
    secret-access-key: AgAhTJKB+F4KMLwQEiBnAy6zrEKhHGP6yyBaVdnLPHto6DNzRvdRXTY0fx95sS/lN8q3jOTMUhPtSsFAsnubRSfoh86pNOQWKRS16XDaoHNHk8iVGDuKNhDcs+sm6BKfDQfl0iDwaBzn6Xk4XDlUEZ5ou1rOJL5Yc6pwjS6wgJqHpOR8g1PzvuW0DvBmKI7H26l8vt68vIGv50CEyZnNx8SYjA5oj/UXbngCjqvJB/iAs5lqnxmb7LlDYRA6BEJeCsZO7kCBuQLrYHNiK/tIVQCZ0T+LC8dy61oKBkLA90J6G9kWzj+WosImlElOcOMgrHxmtCgQdOvj3wFlC3m1eSdBqwesXEsm5kq7dHOG0GWOyXVpj8IXUOZDyJgzsrQimqGG7XgpCBiE1oR5GRsZ6ECknyhLFA2qITkvlk+j5IfnTOFB73CUU7NMS2Ryo8ePpPABKjsUPRTflOPvQo4zu9lc/oeN8+vhH1hLMW4SSDdq/lwfUNPf+Y4lIh+Bt3KVL91J8RGXsX/E2z9EseU89VvAttNInsPx45LsdUnM0Hmd3ALvlRAsX8DtreRiJlAMW9j5x5mEWUu5jX0qg7Kh6ybzuqiz2laAdmrCVU4Zi7trw0LlvvayD3wjvo03UQOfL0LfMSv6VCfn6GbnMaEnUst5QoykuM6l4P1w6YEj5jyufJNibbXyx1xblsTwegXJYbxGXekViJ+Wr+Ct3YkZ0h2waXu58cBjgGWgGf2nM59mViZRgnrN4z6Q07NAOrQtPDQnBmklFIxtrFbqw2Os9JuN
  template:
    metadata:
      name: gokapi-r2
      namespace: share
