---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rest-server-htpasswd
  namespace: backups
spec:
  encryptedData:
    htpasswd: AgCj0YFNwHTGGqqdrOaAUA7J3OePjunWyipdzCSiLSjv8nJtdUUm8GZOdLkma4PmGPIJFSHDPHLfNUCGepr0Q9iFYssyat4aRYcZBZq2NQ76vzlrIaKM4HtA6ftpJruQe8Q3fY0WtYC123+u3d6i+ifGNe+fpRagKNBnGf8TKbbTjhzL2or7SBBdRBUyRGkiPGC7CuQThQK9EyV6wQZ3JQj7EDROquSI7ik1OMVR4j2LYzE5ThmeTrTdMSgIiVwhkgaugQaT3L/OEtDYojA3sjZGrTGb+5xbF/2/kouk2F52N7Uz85BXblTnwlsCb4aC5rGGtdagyKH6CBLw18R5QWEfICZmSbAQJJZzp8JqlOlHw6BDViu4HUZlQV+xl3TuG5/HqPM5iuil/GSyZ+LsZb4QwD0Vx4uq2bpxUFh+gs0buKc75632uDhWzRtM/Fi/d+v84nXVRw7TCbarpKGB2UQ/nv8yQRnt8d8TL6kRx7vbUPUHE6XL8+y8nT1clwE6Ul5fvpFs5UQ32AgIBvNGKeL8AD706dwiGNanCEFO4+6OEf4sG/OjKIZDLaQddPJFzhutROV2dwP8PLKEP+IWoeJigdEy7IAejqrHixH2UKnaTgxYv3Y6dwkE4D+kFUS0f+5nO1sAHeE2HWAzmx4QAwoCc8bJpXXB312/39eZzfakKGG0l/p9rKEjisAJVgxMVWpR7AmJRwHbCsUaBVZXYcDG9ZPWZQuyG5ZKfqVmNG+9XvEwjVNyEDMyb42nQpW+c5X+3+sC1WN4YTBJbCW5nmq4M9UjMG0q2nkQy/G1bKHEUbEuuPbbHDwWBKcKW7dUF8lJSkHY8kxFClWGZf0vFSUXJ7yti1ar9mCKx01wMocTq3BcGaCcYbCQcrMll6M/79jJCjpir4CDHJ+cxl5ml89BDUqiwcktz5fkiLu7MVAPxsKsVMho5WnZLZRlvUEQoX8AkE+OfKb/g4k6gIk5UxpM3GcjrBEXzMVwnZPF7a4gzlyniJNdT2Xw1KGqvZCOk3wZLxVfh0t3ottI7xwdzK/277+mNal02uoM7yScbjv5XuSIU1JMVMkw0H4rxplZoA==
  template:
    metadata:
      name: rest-server-htpasswd
      namespace: backups
