---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rest-server-htpasswd
  namespace: backups
spec:
  encryptedData:
    htpasswd: AgBgT20kFUZOHCzIjsoUpqvMDhYRJv90dL99JPgxvtQiCIm4Vk2jPkkH0/uLvNbbaO/0rmI6c7h2ovbOQsWR9s04Z83UfmzTK1FH1zHbuV7jc5YJq9eHW76JlpNej0Q/dX+Qyy5uoAy6Wka531l3xH50tMa+3zgXxvbVgWAfGgdM5+Pozwd3b65LriP3H37FBecW3pbgbZ4/+oVWIgGvTrDeMEf6/YctnRmzpnPncjQWVln+okiMjrKiopceVsIOR8OcaNj6vZEWXhKP5mfwo7dmaFzEImC8n826NVtrp23KHmIKbJEbqXl8i3AlJNux/DsFGZQ5TFtTseE3kv94OivMuu0gRX3LuwXQmDixhY2FwkeTt1EPoO1QTGYu0UwZttJiiHMjRb3tFhwtsM+Qhx5AgCDBtB3zzcT4BGNPNy37X20gXAYpqswr0mpsKzOZKQ16OT1BM2hgxlOJYDqCGE7DhiKuTXVbqSrmRVKwbaw2BPsfISdAQ+Wd296sKhkJxpxGsWpaVPFSqndJ6iv8DnaXF8cmJK1hALM7h3wkUviCXsN181mIPN0/sW1uCW7M6o1lkjpXZMM1qVXG8zQ7u01k68wbIkX43I4h1Dl+J5E5SLz3A9A8/hTzsPsyqCzmgvzuvBmFM8yImk9R0viEZsfwdxLoTSTuwFpKDKL9Ydep+ODS8wAqAzNekomk86yHoPx+81GQi2xdN6jML/jvRV9qPxLywFJwKJh78dEGWz9izDj1NoY3XZCjoop9j1BgyEB1KHfgdADwWpWjKnV5s0nZocrPiG9bjegY5BZd9XiIioXbcsq3MvCqmBGAMOq7Xhkz29Bk/15XGdR0HwH/0it3eRhit5ecErQWOiL+P//vHqO/BrTP0BI5KUpo5IB9rmiIqP4fAhXbXblEWzR47Wz6JDQdOvx1kbklPyxhISWX1mKXT9EyU9mKSwzpvP61MzJTX4HIWvf9e/7kBmrf6VIcIa0=
  template:
    metadata:
      name: rest-server-htpasswd
      namespace: backups
