---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rest-server-htpasswd
  namespace: backups
spec:
  encryptedData:
    htpasswd: AgAhi2AfOkom1+Y+h6t0prtyHwbnEexhFP62cd4rWKRipALM6YOowFalrD5iaZDvmQZkBSFk88eNTZ8r2RxskcIxt9ss35338LzN1Ip3uIvV9fOuVCm+oqg4IXrDNr7PJ11ZKEorfi00Z+C1yjrea9bFgr2dRvbfSfsHsvtxPXgwTgLf8NkCMGXl5OtJIbt7eiHPAv2RyEY5LsB8b+R4n7p1rHdm6BY/KXbX4tFIHmXJvIj1I39YN8Ok8h+QYPW/aKa/pKaRmzDv8I1fzqcMi5QRPRIuQAIxmaFy663GqsaMKHj+q3h79XrwEdRYrek4G3JRUWwpm9/aELVPxks2kct3qUFq/qKFaCSz93gR127XxwVs37aESsi3eNwNay0mEbTm1YbTaAba/TNLyiX+kJ94TpgGQ84vGbAOgIKXG38VmlNHHYN3azReOJifbFQLDr4uj8JzbbfqYbV4fz2CcbpumQ+owxcoRbXgu5/bTcKrR1gvmr5kIgGmo479nMVo+S1NgADfOVGF9COhsL1THkTL9oSMwy2KK1NAiToVrLD3jchVR4GIQ7xrR811weuLobrI07eIpa5JjiLykwBHXNYPcujX64s5CKJgZJ1wHtkJI/OcUiAmvHC0OvgEZFnUoarzCxR8ivLEG6+oJOzZAwCrZM/WZzUp2dO4fC10CwsnBONoZZoFq3oMMnjWBBZAW3h+Nb0bSasFkzW8YUXbfKMoBeIPnj0uD34P3suASaiULhmXkl/2MWW6ZfFqqAKTxxlb+TMHUPAMmcBMyxPp+lrCsalGKMptTmiMvow0tw9OnAseE0SxY0j8pL/YJmgIgr1oAYCJBjffOv6t2q44RNHDv3DAWl1kJLxmPsTxcqJf0ZO4EKL/T1n6+NMPc5gJZQoci5wYTVgH9mFJYs5rDAPsad0Ny4GemDINR0pzvgZjO8XDLD9HemNc5eTwQaagWi65B5EhljNB+4bnQkewC+VzHQJWpiUc1KiPgM30lCUrkAGxEqGu99WrOsm/3VH8CzLCsdh5OD4R
  template:
    metadata:
      name: rest-server-htpasswd
      namespace: backups
