apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backups
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JersyJ/lichnovsky.eu.git
    targetRevision: main
    path: apps/backups
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: backups
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
